// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// laridae.cpp
SEXP lari_new_cpp(strings attr_names);
extern "C" SEXP _laridae_lari_new_cpp(SEXP attr_names) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_new_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(attr_names)));
  END_CPP11
}
// laridae.cpp
strings lari_attr_names_cpp(SEXP xp);
extern "C" SEXP _laridae_lari_attr_names_cpp(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_attr_names_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// laridae.cpp
integers lari_add_points_cpp(SEXP xp, doubles x, doubles y, doubles_matrix<> PA);
extern "C" SEXP _laridae_lari_add_points_cpp(SEXP xp, SEXP x, SEXP y, SEXP PA) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_add_points_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(PA)));
  END_CPP11
}
// laridae.cpp
integers lari_add_segments_cpp(SEXP xp, integers s0, integers s1);
extern "C" SEXP _laridae_lari_add_segments_cpp(SEXP xp, SEXP s0, SEXP s1) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_add_segments_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<integers>>(s0), cpp11::as_cpp<cpp11::decay_t<integers>>(s1)));
  END_CPP11
}
// laridae.cpp
int lari_remove_segments_cpp(SEXP xp, integers s0, integers s1, integers sid);
extern "C" SEXP _laridae_lari_remove_segments_cpp(SEXP xp, SEXP s0, SEXP s1, SEXP sid) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_remove_segments_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<integers>>(s0), cpp11::as_cpp<cpp11::decay_t<integers>>(s1), cpp11::as_cpp<cpp11::decay_t<integers>>(sid)));
  END_CPP11
}
// laridae.cpp
int lari_remove_points_cpp(SEXP xp, integers ids);
extern "C" SEXP _laridae_lari_remove_points_cpp(SEXP xp, SEXP ids) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_remove_points_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<integers>>(ids)));
  END_CPP11
}
// laridae.cpp
list lari_tables_cpp(SEXP xp, int domain);
extern "C" SEXP _laridae_lari_tables_cpp(SEXP xp, SEXP domain) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_tables_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(domain)));
  END_CPP11
}
// laridae.cpp
list lari_counts_cpp(SEXP xp);
extern "C" SEXP _laridae_lari_counts_cpp(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_counts_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// laridae.cpp
int lari_refine_cpp(SEXP xp, double min_angle, double max_area, double min_edge_length, SEXP size_fun, doubles grid_x, doubles grid_y, doubles grid_z, int domain, doubles seed_x, doubles seed_y, double max_steiner);
extern "C" SEXP _laridae_lari_refine_cpp(SEXP xp, SEXP min_angle, SEXP max_area, SEXP min_edge_length, SEXP size_fun, SEXP grid_x, SEXP grid_y, SEXP grid_z, SEXP domain, SEXP seed_x, SEXP seed_y, SEXP max_steiner) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_refine_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<double>>(min_angle), cpp11::as_cpp<cpp11::decay_t<double>>(max_area), cpp11::as_cpp<cpp11::decay_t<double>>(min_edge_length), cpp11::as_cpp<cpp11::decay_t<SEXP>>(size_fun), cpp11::as_cpp<cpp11::decay_t<doubles>>(grid_x), cpp11::as_cpp<cpp11::decay_t<doubles>>(grid_y), cpp11::as_cpp<cpp11::decay_t<doubles>>(grid_z), cpp11::as_cpp<cpp11::decay_t<int>>(domain), cpp11::as_cpp<cpp11::decay_t<doubles>>(seed_x), cpp11::as_cpp<cpp11::decay_t<doubles>>(seed_y), cpp11::as_cpp<cpp11::decay_t<double>>(max_steiner)));
  END_CPP11
}
// laridae.cpp
int lari_step_cpp(SEXP xp, int n);
extern "C" SEXP _laridae_lari_step_cpp(SEXP xp, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_step_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// laridae.cpp
doubles_matrix<> lari_input_segments_cpp(SEXP xp);
extern "C" SEXP _laridae_lari_input_segments_cpp(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(lari_input_segments_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_laridae_lari_add_points_cpp",      (DL_FUNC) &_laridae_lari_add_points_cpp,       4},
    {"_laridae_lari_add_segments_cpp",    (DL_FUNC) &_laridae_lari_add_segments_cpp,     3},
    {"_laridae_lari_attr_names_cpp",      (DL_FUNC) &_laridae_lari_attr_names_cpp,       1},
    {"_laridae_lari_counts_cpp",          (DL_FUNC) &_laridae_lari_counts_cpp,           1},
    {"_laridae_lari_input_segments_cpp",  (DL_FUNC) &_laridae_lari_input_segments_cpp,   1},
    {"_laridae_lari_new_cpp",             (DL_FUNC) &_laridae_lari_new_cpp,              1},
    {"_laridae_lari_refine_cpp",          (DL_FUNC) &_laridae_lari_refine_cpp,          12},
    {"_laridae_lari_remove_points_cpp",   (DL_FUNC) &_laridae_lari_remove_points_cpp,    2},
    {"_laridae_lari_remove_segments_cpp", (DL_FUNC) &_laridae_lari_remove_segments_cpp,  4},
    {"_laridae_lari_step_cpp",            (DL_FUNC) &_laridae_lari_step_cpp,             2},
    {"_laridae_lari_tables_cpp",          (DL_FUNC) &_laridae_lari_tables_cpp,           2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_laridae(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
