# Generated by cpp11: do not edit by hand

lari_new_cpp <- function(attr_names) {
  .Call(`_laridae_lari_new_cpp`, attr_names)
}

lari_attr_names_cpp <- function(xp) {
  .Call(`_laridae_lari_attr_names_cpp`, xp)
}

lari_add_points_cpp <- function(xp, x, y, PA) {
  .Call(`_laridae_lari_add_points_cpp`, xp, x, y, PA)
}

lari_add_segments_cpp <- function(xp, s0, s1) {
  .Call(`_laridae_lari_add_segments_cpp`, xp, s0, s1)
}

lari_remove_segments_cpp <- function(xp, s0, s1, sid) {
  .Call(`_laridae_lari_remove_segments_cpp`, xp, s0, s1, sid)
}

lari_remove_points_cpp <- function(xp, ids) {
  .Call(`_laridae_lari_remove_points_cpp`, xp, ids)
}

lari_tables_cpp <- function(xp, domain) {
  .Call(`_laridae_lari_tables_cpp`, xp, domain)
}

lari_counts_cpp <- function(xp) {
  .Call(`_laridae_lari_counts_cpp`, xp)
}

lari_refine_cpp <- function(xp, min_angle, max_area, min_edge_length, size_fun, grid_x, grid_y, grid_z, domain, seed_x, seed_y, max_steiner) {
  .Call(`_laridae_lari_refine_cpp`, xp, min_angle, max_area, min_edge_length, size_fun, grid_x, grid_y, grid_z, domain, seed_x, seed_y, max_steiner)
}

lari_step_cpp <- function(xp, n) {
  .Call(`_laridae_lari_step_cpp`, xp, n)
}

lari_input_segments_cpp <- function(xp) {
  .Call(`_laridae_lari_input_segments_cpp`, xp)
}
