# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CGAL point triangulation (unconstrained)
#'
#' `tri_xy` CGAL vertex index
#'
#' First method uses uses a faces iterator to extract the vertex->info for
#' each face. A Delaunay triangulation has both finite and infinite faces
#' (see CGAL documentation). The infinite faces join to an external, infinite
#' vertex, so the finite_faces_iterator just includes the internal faces.
#'
#' vertex index
#' @param x coordinate vector
#' @param y coordinate vector
#' @export
#' @name tri_xy
#' @export
tri_xy <- function(x, y) {
    .Call('_cgalgris_tri_xy', PACKAGE = 'cgalgris', x, y)
}

#' `tri_xy1` CGAL vertex index MP version#2
#'
#' This method uses a vertex iterator instead of a faces iterator.
#'
#' @export
#' @name tri_xy
tri_xy1 <- function(x, y) {
    .Call('_cgalgris_tri_xy1', PACKAGE = 'cgalgris', x, y)
}

#' `tri_xy2` CGAL vertex index MP version#3
#'
#' This is the long-hand way, using an iteration over all faces, checking
#' whether they are finite or not, and accessing the face.vertex info by
#' dereferencing pointers to each vertex of the face.
#'
#' @export
#' @name tri_xy
tri_xy2 <- function(x, y) {
    .Call('_cgalgris_tri_xy2', PACKAGE = 'cgalgris', x, y)
}

