# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CGAL test
#'
#' test CGAL
#' @export
ach <- function() {
    .Call('_cgalgris_ach', PACKAGE = 'cgalgris')
}

#' CGAL1
#'
#' 1
#' @export
apoint <- function(x, y) {
    .Call('_cgalgris_apoint', PACKAGE = 'cgalgris', x, y)
}

#' CGAL test2
#'
#' test2 CGAL
#' @export
pas <- function() {
    .Call('_cgalgris_pas', PACKAGE = 'cgalgris')
}

#' CGAL vertex index
#'
#' vertex index
#' @export
tri_xy <- function(x, y) {
    .Call('_cgalgris_tri_xy', PACKAGE = 'cgalgris', x, y)
}

#' CGAL vertex index
#'
#' vertex index
#' @export
ctri_xy <- function(x, y) {
    .Call('_cgalgris_ctri_xy', PACKAGE = 'cgalgris', x, y)
}

